import React from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Printer, Copy, Check } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { toast } from 'sonner';

export const ProposalCard = ({ content }) => {
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(content);
        setCopied(true);
        toast.success("Proposal copied to clipboard");
        setTimeout(() => setCopied(false), 2000);
    };

    const handlePrint = () => {
        // Create a hidden iframe or new window for printing specifically the proposal content
        const printWindow = window.open('', '_blank');
        printWindow.document.write(`
            <html>
                <head>
                    <title>Project Proposal - Catalance</title>
                    <style>
                        body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; line-height: 1.6; color: #333; }
                        h1 { color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
                        h2 { color: #334155; margin-top: 24px; }
                        strong { color: #0f172a; }
                        ul { padding-left: 20px; }
                        li { margin-bottom: 8px; }
                        .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #64748b; text-align: center; }
                    </style>
                </head>
                <body>
                    ${document.getElementById('proposal-content').innerHTML}
                    <div class="footer">Generated by Catalance AI Assistant</div>
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.print();
    };

    return (
        <Card className="mx-auto w-[min(92vw,1180px)] overflow-hidden border border-zinc-200/80 bg-white shadow-[0_20px_60px_-28px_rgba(15,23,42,0.35)] animate-in fade-in slide-in-from-bottom-4 duration-700 dark:border-zinc-800 dark:bg-zinc-900">
            {/* Header / Brand Strip */}
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-200/80 bg-gradient-to-r from-slate-950 via-slate-900 to-slate-800 px-4 py-3 text-white sm:flex-nowrap sm:px-5 lg:px-6">
                <div className="flex min-w-0 items-center gap-3">
                    <div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white/10 ring-1 ring-white/10 sm:h-10 sm:w-10">
                        <FileText className="h-5 w-5 text-white" />
                    </div>
                    <div className="min-w-0">
                        <h3 className="truncate text-[11px] font-extrabold uppercase tracking-[0.22em] text-white/95 sm:text-xs lg:text-[13px]">Catalance</h3>
                        <p className="text-[10px] font-medium text-white/55 sm:text-[11px] lg:text-xs">AI Generated Proposal</p>
                    </div>
                </div>
                <div className="flex items-center gap-1.5 self-end sm:self-auto sm:gap-2">
                    <Button
                        variant="ghost"
                        size="sm"
                        className="h-9 w-9 rounded-xl border border-white/10 bg-white/5 text-white/80 hover:bg-white/10 hover:text-white"
                        onClick={handleCopy}
                    >
                        {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                        <span className="sr-only">Copy</span>
                    </Button>
                    <Button
                        variant="ghost"
                        size="sm"
                        className="h-9 gap-2 rounded-xl border border-white/10 bg-white/5 px-3 text-[11px] font-semibold text-white/85 hover:bg-white/10 hover:text-white sm:px-4 sm:text-xs"
                        onClick={handlePrint}
                    >
                        <Printer className="h-4 w-4" />
                        <span className="hidden sm:inline">Download PDF</span>
                    </Button>
                </div>
            </div>

            <CardContent className="px-4 py-5 sm:px-6 sm:py-6 lg:px-8 lg:py-8 xl:px-10 2xl:px-12 2xl:py-10">
                <div
                    id="proposal-content"
                    className="prose prose-slate max-w-none prose-headings:font-semibold prose-h1:mb-4 prose-h1:text-[1.45rem] sm:prose-h1:text-[1.65rem] lg:prose-h1:text-[1.9rem] 2xl:prose-h1:text-[2.05rem] prose-h1:leading-tight prose-h1:border-b prose-h1:pb-3 prose-h1:border-zinc-200 prose-h2:mt-6 prose-h2:mb-3 prose-h2:text-[1rem] sm:prose-h2:text-[1.1rem] lg:prose-h2:text-[1.2rem] 2xl:prose-h2:text-[1.3rem] prose-h2:leading-snug prose-p:my-3 prose-p:leading-7 prose-li:my-1.5 prose-ul:pl-5 prose-ol:pl-5 prose-a:text-orange-600 prose-a:underline-offset-4 hover:prose-a:text-orange-700 dark:prose-invert dark:prose-h1:border-zinc-700 dark:prose-a:text-amber-400"
                >
                    <ReactMarkdown>
                        {content}
                    </ReactMarkdown>
                </div>
            </CardContent>

            <CardFooter className="flex items-center justify-center border-t border-zinc-200/80 bg-zinc-50 px-4 py-3 text-center text-[11px] leading-5 text-zinc-500 dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-400 sm:px-6">
                This document is a preliminary draft based on your requirements.
            </CardFooter>
        </Card>
    );
};
