import React from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Printer, Copy, Check } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { toast } from 'sonner';

export const ProposalCard = ({ content }) => {
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(content);
        setCopied(true);
        toast.success("Proposal copied to clipboard");
        setTimeout(() => setCopied(false), 2000);
    };

    const handlePrint = () => {
        // Create a hidden iframe or new window for printing specifically the proposal content
        const printWindow = window.open('', '_blank');
        printWindow.document.write(`
            <html>
                <head>
                    <title>Project Proposal - Catalance</title>
                    <style>
                        body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; line-height: 1.6; color: #333; }
                        h1 { color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
                        h2 { color: #334155; margin-top: 24px; }
                        strong { color: #0f172a; }
                        ul { padding-left: 20px; }
                        li { margin-bottom: 8px; }
                        .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #64748b; text-align: center; }
                    </style>
                </head>
                <body>
                    ${document.getElementById('proposal-content').innerHTML}
                    <div class="footer">Generated by Catalance AI Assistant</div>
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.print();
    };

    return (
        <Card className="w-full max-w-3xl mx-auto shadow-xl border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* Header / Brand Strip */}
            <div className="bg-slate-900 text-white p-4 flex justify-between items-center">
                <div className="flex items-center gap-2">
                    <div className="h-8 w-8 rounded bg-indigo-500 flex items-center justify-center">
                        <FileText className="h-5 w-5 text-white" />
                    </div>
                    <div>
                        <h3 className="font-bold text-sm tracking-wide uppercase">Catalance</h3>
                        <p className="text-[10px] text-slate-400">AI Generated Proposal</p>
                    </div>
                </div>
                <div className="flex gap-2">
                    <Button
                        variant="ghost"
                        size="sm"
                        className="text-slate-300 hover:text-white hover:bg-slate-800"
                        onClick={handleCopy}
                    >
                        {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                        <span className="sr-only">Copy</span>
                    </Button>
                    <Button
                        variant="ghost"
                        size="sm"
                        className="text-slate-300 hover:text-white hover:bg-slate-800 gap-2"
                        onClick={handlePrint}
                    >
                        <Printer className="h-4 w-4" />
                        <span className="text-xs font-medium">Download PDF</span>
                    </Button>
                </div>
            </div>

            <CardContent className="p-8 md:p-12">
                <div id="proposal-content" className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-semibold prose-h1:text-3xl prose-h1:border-b prose-h1:pb-4 prose-h1:border-slate-100 dark:prose-h1:border-zinc-700 prose-a:text-indigo-600 dark:prose-a:text-indigo-400">
                    <ReactMarkdown>
                        {content}
                    </ReactMarkdown>
                </div>
            </CardContent>

            <CardFooter className="bg-slate-50 dark:bg-zinc-950 p-4 border-t border-slate-100 dark:border-zinc-800 flex justify-center text-xs text-slate-400">
                This document is a preliminary draft based on your requirements.
            </CardFooter>
        </Card>
    );
};
